apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeapi
  labels:
    app: coffeeapi
spec:
  selector:
    matchLabels:
      app: coffeeapi
  replicas: 1
  template:
    metadata:
      labels:
        app: coffeeapi
    spec:
      containers:
      - image: gcr.io/digisense-293411/coffeeapi
        name: coffeeapi
        ports:
        - containerPort: 80
      restartPolicy: Always